version: "3"

services:
  logstash-fortigate:
    build: ${PWD}/logstash-fortigate
    container_name: logstash-fortigate
    hostname: logstash-fortigate
    ports:
      - "9004:9004/udp"
    volumes:
      - ${PWD}/logstash-fortigate/pipeline:/usr/share/logstash/pipeline:ro
    restart: unless-stopped

  logstash-meraki:
    build: ${PWD}/logstash-meraki
    container_name: logstash-meraki
    hostname: logstash-meraki
    ports:
      - "9005:9005/udp"
    volumes:
      - ${PWD}/logstash-meraki/pipeline:/usr/share/logstash/pipeline:ro
    restart: unless-stopped

  logstash-ciscoise:
    build: ${PWD}/logstash-ciscoise
    container_name: logstash-ciscoise
    hostname: logstash-ciscoise
    ports:
      - "9006:9006/udp"
    volumes:
      - ${PWD}/logstash-ciscoise/pipeline:/usr/share/logstash/pipeline:ro
    restart: unless-stopped

  logstash-windows:
    build: ${PWD}/logstash-windows
    container_name: logstash-windows
    hostname: logstash-windows
    ports:
      - "9007:9007"
    volumes:
      - ${PWD}/logstash-windows/pipeline:/usr/share/logstash/pipeline:ro
    restart: unless-stopped

  loki:
    image: grafana/loki:main
    container_name: loki
    hostname: loki
    volumes:
      - ${PWD}/loki/local-config.yml:/etc/loki/local-config.yml:ro
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    ports:
      - "3001:3000"
    restart: unless-stopped